# DARKER ON LEFT SETUP/DESK (SINGLE 4K LG MONITOR)
monitor=eDP-1, 1920x1200@60, 0x0, 1.0, bitdepth, 10
monitor=DP-3, 3840x2160@60, -3072x0, 1.25, transform, 0, bitdepth, 10

workspace = 1, monitor:eDP-1
workspace = 2, monitor:eDP-1
workspace = 3, monitor:DP-3
workspace = 4, monitor:DP-3
workspace = 5, monitor:DP-3
workspace = 6, monitor:DP-3
workspace = 7, monitor:DP-3
workspace = 8, monitor:DP-3
workspace = 9, monitor:DP-3
workspace = 0, monitor:DP-3
