# ODIN ON LEFT SETUP/DESK

# 1.0 scale (positions in actual pixels)
# Layout left-to-right: HDMI-A-1 | DP-2 | DP-1
# monitor=DP-1, 3840x2160@60, 0x0, 1.0, bitdepth, 10
# monitor=DP-2, 2560x1440@59.95, -2560x360, 1.0, bitdepth, 10
# monitor=HDMI-A-1, 3840x2160@60, -6400x0, 1.0, bitdepth, 10

# 1.5 scale for 4K monitors (logical: 2560x1440); DP-2 stays 1.0
# Layout left-to-right: HDMI-A-1 | DP-2 | DP-1
monitor=DP-1, 3840x2160@60, 0x0, 1.5, bitdepth, 10
monitor=DP-2, 2560x1440@59.95, -2560x0, 1.0, bitdepth, 10
monitor=HDMI-A-1, 3840x2160@60, -5120x0, 1.5, bitdepth, 10

workspace = 1, monitor:DP-1
workspace = 2, monitor:DP-1
workspace = 3, monitor:DP-2
workspace = 4, monitor:DP-2
workspace = 5, monitor:DP-1
workspace = 6, monitor:DP-1
workspace = 7, monitor:DP-1
workspace = 8, monitor:DP-1
workspace = 9, monitor:DP-1
workspace = 0, monitor:HDMI-A-1
