# AUTOSTART

exec-once = swww-daemon
exec-once = quickshell 2>/dev/null
exec-once = mako
exec-once = vicinae server
exec-once = nextcloud --background
exec-once = eval $(gnome-keyring-daemon --start --components=secrets)
exec-once = systemctl --user start hyprpolkitagent
