#!/usr/bin/env bash
# @vicinae.schemaVersion 1
# @vicinae.title Use US International Keyboard Layout
# @vicinae.mode silent
# @vicinae.icon 🌐
# @vicinae.keywords ["keyboard", "layout", "us", "international", "intl", "dead keys"]
# @vicinae.description Switch to the US International layout with dead keys

exec "$HOME/.indie-dawg-dots/archlinux/bin/keyboard-layout" intl
